### ISSUE TITLE
Password Encryption

### ISSUE THREAD

**Issue by benagueros** [FitLifeApp/FitLifeApp.github.io#1]
Figure out how to encrypt passwords for log in.

**Comment by benagueros** [comment]
Javax.crypto.Cipher appears to be a cndidate for password encryption. This post introduces it with an example: https://stackoverflow.com/questions/1132567/encrypt-password-in-configuration-files

**Comment by RBeaver** [comment]
Username/Password encryption done
XML save files also encrypted.
