### ISSUE TITLE
Graphics Research

### ISSUE THREAD

**Issue by benagueros** [FitLifeApp/FitLifeApp.github.io#13]
Explore updates graphics libraries like JavaFX to improve the apps aesthetics.

**Comment by benagueros** [comment]
JavaFX is probably worth implementing.

**Comment by benagueros** [comment]
At this point it would be a complete overhaul to integrate java fx. Moving forward with swing. Closing issue.

**Comment by Benmill7** [comment]
Rip JavaFX
