### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by Stefan28BU** [FitLifeApp/FitLifeApp.github.io#22]
logout needs to dispose current window and go to login window

**Comment by benagueros** [comment]
fixed this issue. The problem was that i moved the code out of window manager and into home page but it was still using a Basic Action Listener instead of the Home Listener.

**Comment by benagueros** [comment]
I created a destroy method for the home page that disposes of the window

**Comment by benagueros** [comment]
Closing Issue
